# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4166afb77a57a4d4a3fcf05624cf05e237014be38e842c7b4db759a3da94ea5c3514e89680171e7f71df8fb78c7efa6d869d6958565bc26e6fa9b03aca6d75e9

test:
  secret_key_base: 017ce2d533f605451a198f69ce526a1185bfc35084df75abc834b86b217e77b787eb7652193646635a8f82f6cb842c443fdd4b1422d393571dc645c49687a155

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
